### ISSUE TITLE
Best practice to combine this repo with react-native-bluetooth-serial ?

### ISSUE THREAD

**Issue by hasanej** [infoxicator/react-native-star-prnt#43] opened 2019-07-23 02:31 UTC
I need to combine this repo with this https://github.com/rusel1989/react-native-bluetooth-serial. That's because I have another bluetooth printer other than Star Micronics. I am new to React Native and I need suggestion on what is the best method and how the project structure should be when combined.

**Comment by HunWalk** [comment] 2019-07-24 09:08
Sorry, we currently can not provide an example application|source at the moment, but i can assure you, that this library works at its best.
You have to use your brain a bit and figure out on your own. But in my opinion the documentation is quite enough for the most basic actions. 
Please close this issue, as this is a personal matter, and not targeting any bugs nor recommending features or tweaks.

**Comment by hasaneljabir** [comment] 2019-07-24 13:49
Just try it with creating a fresh React Native project, it works like charm and pretty easy to implement. What I previously to do is combine it with this repository https://github.com/rusel1989/react-native-bluetooth-serial and it gets a little bit tricky. I'll just reopen this issue with other title as current title would be misleading. Anyway thank you for your suggestion @HunWalk

**Comment by HunWalk** [comment] 2019-07-28 22:08
Yeah, because the lib itself already using the bluetooth module to establish connection between devices, sooo expect some weird stuff going on. Could you provide some logs or description or steps to reproduce the problem or an actual description about the stuff that goes on when you link this lib with the BluetoothSerial one? If you want to extend the bluetooth capabilities of this lib..you may have to create your own native module(not from scratch, just fork this and add your stuff) to be able to add some customizations.

**Closed** 2022-06-11 05:55 UTC
